### PR TITLE
Store remember-me cookies in cookies table

### PR DESCRIPTION
**Pull request by karkouch**

### CODE REVIEW

**Comment by markc** [comment]
Perhaps you could email me the exact cookie schema so we are in sync with the table layout. I'm not sure if I have the right one atm.

**Comment by karkouch** [comment]
Hey Mark,

First, thank you for the $50 you sent me.

I used the same schema as in sh.

mysql> SHOW CREATE TABLE cookies;
*************************** 1. row ***************************
       Table: cookies
Create Table: CREATE TABLE `cookies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `accounts_id` int(11) DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  `expire` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;


Best regards!
Rachid

**Comment by karkouch** [comment]
I used the same schema as in sh.

```
Create Table: CREATE TABLE `cookies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `accounts_id` int(11) DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  `expire` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;
```

**Comment by markc** [comment]
Great. Are you perfectly happy with this schema? No changes before it's put to use?

**Comment by karkouch** [comment]
I used the same table layout as in [sh](https://github.com/netserva/sh/blob/0613a58392c9e84a9d7adddb3b57b816fbecc125/bin/setup-db#L88)

```
CREATE TABLE `cookies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `accounts_id` int(11) DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  `expire` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
```

**Comment by karkouch** [comment]
Just the name `cookies` is confusing, I think it should be renamed to something like `remember_me_cookies`.

**Pull request merged**
